In [1]:
# #libraries
# #1-Tensorflow:-speech image recognition, text bases app, time seris,videodetection(Use for Ml,DEEP L)

# #2:-NUMPY (NUMPY AND PANDA ARE USE IN DATA ANALIYSIS,CREAT THE POWERFULL N-DIMENTIONS OF ARRAY,forms the base of other libraries

# like scipy,scikit-learn,Replacement of matlab when uses with scipy matplotlab)

# #3:-scipy is the collection of mathematical algorithem and scientific funtions buil on the numpy extension of python

# high level commands and classes for manipulating and visualizing data,use for mulitdimesion

# #4-panda use in data science data analysis and cleaning use,genral data wrangling, ETL jobs & data storage, used in wide variety 

# of acadamic and commercial domain include statistics ETC,time series-species funtionality
# #5:-matplotlib

In [2]:
# # #numpy
#What is an array
 
# #The array is 1D array and 2D 3D 
# NumPy aims to provide an array object that is up to 50x faster than traditional Python lists.
# # Numpy is the core libary for scientific and numerical computing in python
# #Its provide hight performance multidimensional array object and tools of working arrays
# #in Numpey, dememsions are called axes
# #Differwent between NUmpy and List
# list is ver slow the numpy
# nympy using there contignus memeor


In [3]:
pip install numpy


Note: you may need to restart the kernel to use updated packages.


Basic numpy array

In [4]:
#Mathematical funtion 

import numpy as np#this last name we call elies name
a=np.emath.power([2,4],-6)
a


array([0.015625  , 0.00024414])

In [5]:
import math
np.emath.log(-math.exp(1)) == (1+1j*math.pi)

True

In [6]:
 import numpy as a
 b=a.array([1,2,3])#1d
 c=a.array([[1,2,3],[1,2,3],[1,2,3,]])#3d
 b.ndim #dimesion
print(b,type(b))
 d=a.zeros([2,6])#for inisclise my own weight for we use zero
e=a.ones([5,6])
print(e)
 print(d)
c.shape


[1 2 3] <class 'numpy.ndarray'>
[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


(3, 3)

In [7]:
c=a.array([[1,2,3,4],[1,3,2,5],[1,4,1,6]])
print(c.shape)
print()
print(c)
print()

print(c[1:,:])


(3, 4)

[[1 2 3 4]
 [1 3 2 5]
 [1 4 1 6]]

[[1 3 2 5]
 [1 4 1 6]]


In [8]:
c=a.array([[1,2,3,4],[1,3,2,5],[1,4,1,6]])
print(c)

c[0:2,1:4]

[[1 2 3 4]
 [1 3 2 5]
 [1 4 1 6]]


array([[2, 3, 4],
       [3, 2, 5]])

In [9]:
c=np.arange(0,10,2)
c

array([0, 2, 4, 6, 8])

In [10]:
c=np.linspace(1,10,50)#WE use in deep learnig 
c

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [11]:
import numpy as np
import time
import sys

In [12]:
b=range(100)
print(sys.getsizeof(5)*len(b))

2800


In [13]:
val=2
c.val(c)

AttributeError: 'numpy.ndarray' object has no attribute 'val'

In [ ]:
d=np.arange(100)

print(d.size*d.itemsize)

In [ ]:
size=10000

In [ ]:
s=range(size)
s1=range(size)
s2=np.arange(size)
s3=np.arange(size)


In [ ]:
start=time.time()
result= [(x,y)for x,y in zip(s,s1)]

print("the time use in list",(time.time() - start)*1000)

In [ ]:
start=time.time()
result=s2+s3
print((time.time() -start) * 1000)

In [ ]:
import numpy as np
num = np.array([1,2,3])
print("the first rank array",num)
num1 =np.array([[1,2,3],[1,2,3]])
print('second ranke array',type(num1),num1)
tup=np.array((1,2,3,4))
print("thsi is the tuple ", tup)


In [ ]:
import numpy as np
num = np.array([[1,2,3],[3,4,5]],dtype=np.float64)
add = np.array([[5,6,5],[2,5,6]])
print(num + add)

In [ ]:
import numpy as np
num = np.array([[1,2,3],[3,4,5]],dtype=np.complex64)
add = np.array([[5,6,5],[2,5,6]])
print(num + add)

In [ ]:
print("concatenation example")
print (np.char.add(["ketan--","hi"],["salian","-jsh"]))
print (np.char.multiply("ketan--",3))


In [ ]:
x=range(5)
print(x)

y=np.arange(5)
print(y)

In [ ]:
text='ketan salian'
x=text.encode('utf_16')
print(x)
y=x.decode('utf_16')
print(y)

In [ ]:
text= b'\xff\xfek\x00e\x00t\x00a\x00n\x00 \x00s\x00a\x00l\x00i\x00n\x00a\x00' 

y=x.decode("utf_16 ")#We use the encode an decode to hide the from the user
print(y)

In [ ]:
x= np.array(["keetan","neeeta"])
print(np.char.strip(x,chars='e'))

In [ ]:
x=np.char.capitalize(["hello" ,"world"])
x


In [ ]:
inout=np.array(['keetan ','saleian'])
np.char.strip(inout)
print(np.char.strip(inout,'e'))

In [ ]:
print(np.char.lstrip(["ketan","saleian"],"e"))

In [ ]:
print(np.char.replace('he is the good dancer','is','was'))

In [ ]:
print(np.char.center("ketan",66,fillchar='*'))

# PART2 NUMPY ARRAY


# #ARRAY MANIPULATION

In [ ]:
import numpy as np

In [ ]:
a=np.arange(15)
print("we creat the array")
print(a)
print("now we reshape the array in matrix form")

b=a.reshape(3,5)#if we can not use perfact value in reshape its we give error
print(b)


In [ ]:
print(b.flatten())#its bring the b array in orignal position

In [ ]:
print(b.flatten('f'))

In [ ]:
a=np.arange(12).reshape(3,4)
print(a)

In [ ]:
a.transpose()#Equivalent function its revers the data

In [ ]:
a=np.arange(8).reshape(2,2,2)
print(a)


In [ ]:
np.rollaxis(a,2) #its use to roll the value

In [ ]:
np.swapaxes(a,1,2)#its use to swap the value 

# NUMPY ARITHEMATIC OPRATION

In [ ]:
a=np.arange(9).reshape(3,3)
print(a)

In [ ]:
# a= np.array([1,2,3,4,5,6])
# a.reshape(3,2)


In [ ]:
b=np.array([10,10,10])
b


In [ ]:
np.add(a,b)


In [ ]:
np.subtract(a,b)

In [ ]:
np.multiply(a,b,)

# slicing

In [ ]:
a=np.arange(10)
a

In [ ]:
a[4:8]

In [ ]:
s=slice(2,9,3)#its start from2 end at 9 last take the odd num 
a[s]

# itration over array

In [ ]:
a = np.arange(0,18,2).reshape(3,3)
for x in np.nditer(a): #this use for itrate the valu
     print(x)


# ITRATION ORDER IN C TYPE TO F TYPE


In [ ]:
print(a)
for x in np.nditer(a, order='c'):
    print(x,)

print()

for x in np.nditer(a, order='f'):
    print(x)
    

# JOINING ARRAY

In [ ]:
a = np.array([[1,2],[3,4]])
print("first aray",a)

In [ ]:
b = np.array([[5,6],[7,8]])
print("second array",b)

In [ ]:
print(np.concatenate([a,b]))

In [ ]:
print(np.concatenate([a,b],axis=1))

In [ ]:
a= np.arange(9)
print(a)
print(np.split(a,3))#split we use to convert the arange in give split value
np.split(a,[4,5])

In [ ]:
np.split(a,[4,7])

# RESIZING THE ARRAY

In [ ]:
a = np.array([[1,2,3],[4,5,6]])
print(a)
print(np.shape(a))
print("\n")

b=np.resize(a,[3,2])#its use to resize the shape 
print(b)
print(b.shape)
print('\n')
b=np.resize(a,[4,2])#you can use and (r,c)to resize without error it we repet the value but no give you the error.
print(b,"\n")
print(b.shape)

# HISTOGRAM

In [ ]:
from matplotlib import pyplot as plt
import numpy as np
a=np.array([10,25,6,45,90,35,20,0,30,50])
plt.hist(a,bins=[0,20,40,60,80,100])
plt.title("histogram")
plt.xlabel("x-Histogram")
plt.show()

        

In [ ]:
plt.hist(a,bins=[0,10,20,40,60,80,100])




# Other UseFull funtion in numpy

In [ ]:
#linespace funtion The numpy.linspace() function returns number spaces evenly w.r.t interval.
#Similar to numpy.arange() function but instead of step it uses sample number.(start, stop, step) 

a=np.linspace(1,10,20)
b=np.linspace(10,20,30)
b=np.sin(a)
plt.stem(a,b)
plt.xlim(1,10)
plt.show()

print(a)

In [ ]:
#SUM AND AXIS
a=np.array([[1,2,3],[4,5,6]])
np.sum(a,axis=0)#its we give you the sum of both axis

In [ ]:
a=np.array([[1,2,3],[4,5,6]])
np.sum(a,axis=1)

In [ ]:
#square root and stander diviation
a=np.array([[1,2,3],[4,5,6]])
print(np.sqrt(a))

np.std(a)

In [ ]:
#log funtion 
a=np.array([[1,2,3],[4,5,6]])
print(np.log10(a))

# NUMPY PRACTISE EXAMPLE

In [ ]:
#Now we are using the numpy and matplotlab for the sin grap

In [ ]:
from matplotlib import pyplot as plt
import numpy as np
x=np.arange(0,3*np.pi,0.1)
print(x)
y=np.sin(x)#We use the sin value in graps
plt.stem(x,y)# you can use any plot typ like STEM PLOT SCATTER ect
plt.title("SIN GRAP")
plt.show()



In [ ]:
#Create a 6*6 two-dimentional array, and let1 and 0 be place alternatively across the diagonals 

In [ ]:
x=np.zeros((6,6),dtype=int)
x[1::2,::2] = 1
x[::2,1::2] = 1

x